### ISSUE TITLE
非好友关系，给对方发消息，监听不到

### ISSUE THREAD

**Issue by chuangzhoucom** [openimsdk/open-im-sdk-web#11]
For example, there are now three users: 'A', 'B', and 'C'
`A 'user logs in based on' OpenMetaOffice Electron ', while' B 'and' C 'obtain' token 'login through' API 'and send messages to' A 'user.' A 'user only listens to' B 'user messages, while' C 'user cannot listen. The' OnConversationChanged 'event will not be triggered
The pull session list method is also invalid for 'openIM. getAllConversationList' and 'openIM. getConversationListSplit'`
During the testing process, did the scenario of deleting all sessions several times and then initiating the session result in the resend message not being received?

**Comment by Bloomingg** [comment]
Please upgrade v3 and try again
