### ISSUE TITLE
请问微信小程序支持吗？

### ISSUE THREAD

**Issue by hongyouqin** [openimsdk/open-im-sdk-web#12]
May I ask if the WeChat mini program supports it? In the WeChat developer tool, the websocket connection reported an error as follows:
![image](https://user-images.githubusercontent.com/37205926/182297961-7cd27f9b-cb4b-4f1f-85a9-bd981af3d2a4.png)

**Comment by Bloomingg** [comment]
支持的，拉取最新版本

**Comment by wdx666** [comment]
微信小程序 openIM.login报错

**Comment by wdx666** [comment]
微信小程序中 openIM.login
![1670473032150](https://user-images.githubusercontent.com/25070683/206355395-ea04ade8-8543-494f-93e3-e9b1ac3b3f02.jpg)

**Comment by Bloomingg** [comment]
> 微信小程序中 openIM.login 报错是什么问题 ![1670473032150](https://user-images.githubusercontent.com/25070683/206355395-ea04ade8-8543-494f-93e3-e9b1ac3b3f02.jpg)

参数不对，ws端口不对。参考：https://doc.rentsoft.cn/#/js_v2/sdk_integrate/sdk_use?id=%e7%99%bb%e5%bd%95

**Comment by wdx666** [comment]
谢谢 有小程序的案例可以参考一下吗
