### ISSUE TITLE
在uni-app中使用的问题

### ISSUE THREAD

**Issue by codepod-x** [openimsdk/open-im-sdk-web#13]
## Question 1
The getPlatform method returns unknown on both the mini program and the app, and the subsequent logic will cause both the app and the mini program to use wx to create websockets. This issue can be temporarily resolved in this way
<img width="362" alt="Screenshot 2022-08-29 PM 3 48 49" src=“ https://user-images.githubusercontent.com/43745492/187151193-c739668d-580b-4096-9b2a-2ac5dc63bbe4.png >
## Question 2
On the WeChat applet side, after logout failed to close websocket, messages could be received after logout. After debugging, it was found that it was a problem to judge logout in handleMessage. When the logout request had been answered, data.event was Logout, but the value circled in the figure was still Login (the logout I called after login). This logout condition was entered after calling logout several times, On the H5 end, there is no such issue. Can we directly determine whether it is a logout instruction based on data. event?
<img width="808" alt="Enterprise WeChat screenshot _80d26063-2a2b-4b7e-ae05-011b25dd9a9c" src=“ https://user-images.githubusercontent.com/43745492/187152106-c4563a60-a9c0-4ddb-bf9f-90d11568aa41.png >
## Question 3
The SDK homepage indicates that it can be used on the uni app, but there are often problems with the app and iOS, which are basically unusable. This may be my personal problem, but I have tried many methods and always encounter various problems. Therefore, I raise a question here, what is the relationship between this SDK and the uni app's SDK, or what is the difference? Currently, in my opinion, this SDK is not easy to use in places other than H5
<img width="916" alt="Enterprise WeChat screenshot edf0b2a9-7134-43e1-b091-7fd7c7f36f24" src=“ https://user-images.githubusercontent.com/43745492/187153915-1b8d9d65-40e5-47b5-b0fa-1de6e3313cf8.png >

**Comment by Bloomingg** [comment]
Please upgrade v3 and try again
