### ISSUE TITLE
微信小程序不支持Worker对象导致心跳失败

### ISSUE THREAD

**Issue by CNunicorn6** [openimsdk/open-im-sdk-web#14]
- name: open-im-sdk
- version: 2.3.0

[WeChat mini program documentation](https://developers.weixin.qq.com/miniprogram/dev/api/worker/Worker.html)
> Worker
> Related documents: [Multi threaded Worker](https://developers.weixin.qq.com/miniprogram/dev/framework/workers.html)
> 
> Worker instance, which can be accessed in the main thread through [wx.createWorker](https://developers.weixin.qq.com/miniprogram/dev/api/worker/wx.createWorker.html) interface acquisition, which can be obtained through the global variable worker in the worker thread.

src/utils/worker.ts
```
function create(fun: any) {
  const blob = new Blob(["(" + fun + ")()"]);
  const url = window.URL.createObjectURL(blob);
  const worker = new Worker(url);
  return worker;
}
```

**Comment by Bloomingg** [comment]
Please upgrade v3 and try again
