### ISSUE TITLE
Regarding token

### ISSUE THREAD

**Issue by zhoushoujian** [OpenIMSDK/Open-IM-SDK-Web#2]
The [doc()](https://doc.rentsoft.cn/client_doc/web_doc.html) only describes that we should take secret to server in order to get token, but doc doesn't tell us how to get secret and how to take secret  to get token, could you describe more details?

**Comment by Bloomingg** [comment]
You can find it in another project:https://github.com/OpenIMSDK/Open-IM-Server/blob/main/config/config.yaml#L131.And we We will soon complete the relevant documentation.
