### ISSUE TITLE
Bug: <no exported member  WsResponse>

### ISSUE THREAD

**Issue by hylsvip** [openimsdk/open-im-sdk-web#33]
### What happened?

I tried to use an example, but I couldn't import WsResponse

import { OpenIMSDK } from 'open-im-sdk';

const OpenIM = new OpenIMSDK();
import { CbEvents } from 'open-im-sdk';
import type { WsResponse } from 'open-im-sdk';

OpenIM.on(CbEvents.OnConnecting, handleConnecting);
OpenIM.on(CbEvents.OnConnectFailed, handleConnectFailed);
OpenIM.on(CbEvents.OnConnectSuccess, handleConnectSuccess);

OpenIM.login({
  userID: 'IM user ID',
  token: 'IM user token',
  platformID: 5,
  wsAddr: 'ws://your-server-ip:10003',
  apiAddr: 'http://your-server-ip:10002',
});

function handleConnecting() {
  // Connecting...
}

function handleConnectFailed({ errCode, errMsg }: WsResponse) {
  // Connection failed ❌
  console.log(errCode, errMsg);
}

function handleConnectSuccess() {
  // Connection successful ✅
}

### What did you expect to happen?

I want to import WsResponse

### How can we reproduce it (as minimally and precisely as possible)?

Try importing WsResponse

### Anything else we need to know?

![image](https://github.com/openimsdk/open-im-sdk-web/assets/48637497/5ed6f780-e274-4cb4-a6a7-f9f21560fa04)

### version

<details>
```console
$ {name} version
# paste output here
```
</details>
1

### Cloud provider

<details>
</details>
1

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by AdminX888** [comment]
open-im-sdk 3.4.0

**Comment by Bloomingg** [comment]
instead
```js
import type { WsResponse } from "open-im-sdk/lib/types/entity"
```
