### ISSUE TITLE
Bug: Emoji in message be shown as unreadable codes when sending or receiving messages though miniapp

### ISSUE THREAD

**Issue by qiaoshangyougeren** [openimsdk/open-im-sdk-web#35]
### What happened?

Emoji in message be shown as unreadable codes when sending or receiving messages though miniapp.

The reason maybe is that there is no TextEncoder/TextDecoder in weixin miniapp .

### What did you expect to happen?

please repair the Encoder/Decoder implemented in sdk for emoji

### How can we reproduce it (as minimally and precisely as possible)?

send text message with emoji though miniapp sdk

### version

<details>
open-im-sdk 3.4.1
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
fixed in `3.5.1-alpha.7`, pleasle update `open-im-sdk` and `oimws`.
