### ISSUE TITLE
Bug: Failed to execute 'decode' on 'TextDecoder': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'.

### ISSUE THREAD

**Issue by PaoPaoYo** [openimsdk/open-im-sdk-web#38]
### What happened?

启动时报错
![image](https://github.com/openimsdk/open-im-sdk-web/assets/56428998/c6d1dd98-050c-48d0-93e9-3ceb0a34c900)

### What did you expect to happen?

正常启动

### How can we reproduce it (as minimally and precisely as possible)?

按文档启动

### version

"open-im-sdk": "^3.5.1-alpha.7"
oimws: 3.5.1-alpha.8

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by PaoPaoYo** [comment]
删除node_modules重新安装就好了

**Comment by hylreg** [comment]
You can use oimws3.5.0 for the time being
