### ISSUE TITLE
If the same userID uses different platformIDs to apply for different tokens and logs in with jssdk, there is a probability that new messages cannot be monitored.

### ISSUE THREAD

**Issue by PaoPaoYo** [openimsdk/open-im-sdk-web#40]
### What happened?

使用同一个userID+2个不同的platformID, 获得到2个不同的token, 在2个浏览器窗口分别使用这些token登录, 并监听新消息(`IMSDK.on(CbEvents.OnRecvNewMessages)`), 会概率性出现 其中一个窗口监听不到新消息

### What did you expect to happen?

两个窗口都能正常使用

### How can we reproduce it (as minimally and precisely as possible)?

1. 使用同一个userID+2个不同的platformID, 获得到2个不同的token(使用api中`/auth/user_token`)
2. openim-server 配置多端登陆为10(`multiLoginPolicy: 10`)
3. 在2个浏览器窗口分别使用这些token登录, 并监听新消息(`IMSDK.on(CbEvents.OnRecvNewMessages)`)
4. 发送消息给第一步的userID
![image](https://github.com/openimsdk/open-im-sdk-web/assets/56428998/da6bac96-938d-4f71-8ee4-76dcd6e456b9)

### version

截止当前的最新版本

### Cloud provider

none

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
It is best to use it only on one side of the mini program. This SDK is not suitable for a large number of users or for simulating multiple terminals. It will be deprecated in version 3.8.
