### ISSUE TITLE
[BUG] IMSDK.getUsersInfo is not a function

### ISSUE THREAD

**Issue by 50mkw** [openimsdk/open-im-sdk-web#47]
### OpenIM Server Version

3.5.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

IMSDK.getUsersInfo is not a function

**Comment by Bloomingg** [comment]
The old version can use `getUsersInfoWithCache` instead.
