### ISSUE TITLE
登录成功后在另外的页面获取历史消息列表为空

### ISSUE THREAD

**Issue by 1369521908** [OpenIMSDK/Open-IM-SDK-Web#5]
![image](https://user-images.githubusercontent.com/32727597/143557907-b11f60fa-8064-4383-8f50-bd661304211c.png)

带登录逻辑的地方的参数
![image](https://user-images.githubusercontent.com/32727597/143558016-5325b0ac-ee23-44e8-98aa-ee0fc7c95670.png)

别的地方调用的参数
![image](https://user-images.githubusercontent.com/32727597/143558083-80aee651-949d-4f93-82cd-9161b11682dc.png)

两个地方的结果对比
![image](https://user-images.githubusercontent.com/32727597/143558405-9139698a-a665-419f-99b9-c228b6f0a229.png)

![image](https://user-images.githubusercontent.com/32727597/143558876-2439575e-572b-42bf-8d9d-5b1920bd6a51.png)

请求参数传递
![image](https://user-images.githubusercontent.com/32727597/143558156-d6a7d24e-52bb-4897-b62b-50197d2e0c42.png)
![image](https://user-images.githubusercontent.com/32727597/143558180-8251338b-defd-4010-af4c-c038f4564ab7.png)

**Comment by Bloomingg** [comment]
请升级最新版本SDK以及最新版本服务端镜像重试

**Comment by 1369521908** [comment]
> 请升级最新版本SDK以及最新版本服务端镜像重试

OK,晚点再试试
