### ISSUE TITLE
web sdk 创建自定义消息  失败

### ISSUE THREAD

**Issue by daywant** [OpenIMSDK/Open-IM-SDK-Web#6]
![36f0f3963cb4e3a807d2e3b8771c0f7](https://user-images.githubusercontent.com/30364461/143976144-2f5b456b-9997-4304-8376-c15a20ef2dbd.png)
![3fe2a551f74e14aa47d1a9e75ecd8df](https://user-images.githubusercontent.com/30364461/143976151-37ca7c2b-376d-4474-8bcc-a09d7daddbe5.png)
试了这几种参数  都提示失败

**Comment by 1369521908** [comment]
试试用JSON.stringify转字符串 
![image](https://user-images.githubusercontent.com/32727597/144184563-25a11e7d-8d11-497f-8baf-0924edc5b216.png)

**Comment by daywant** [comment]
> 试试用JSON.stringify转字符串 ![image](https://user-images.githubusercontent.com/32727597/144184563-25a11e7d-8d11-497f-8baf-0924edc5b216.png)

**Comment by daywant** [comment]
把所有的消息  都改成json字符串  来发送文本消息，解决的这个问题
