### ISSUE TITLE
接收到重复数据，在wsSend函数里面设置onmessage函数存在问题

### ISSUE THREAD

**Issue by woshidag** [OpenIMSDK/Open-IM-SDK-Web#8]
你好，使用SDK测试发现，会有接收到多条重复数据的问题。一路查下去发现每次发送信息都对应 onmessage 进行赋值
private wsSend = (
    params: WsParams,
    resolve: (value: WsResponse | PromiseLike<WsResponse>) => void,
    reject: (reason?: any) => void
  ) => {
...
this.ws!.onMessage(handleMessage);
}

把this.ws!.onMessage(handleMessage);放到createWs是正常的。
这问题在小程序里面尤其严重，每次调用发送相关的函数，接收信息就会多一条。

个人对这SDK也不是很熟悉。都是参照h5 demo 使用。不知道是我使用方式又问题还是确实存在问题。

复现方式：h5 demo 。A退出登录，重新登录。B发送信息给A。A会收到2条重复的信息。

**Comment by Bloomingg** [comment]
已修复
